server:
   port: 7900

eureka:
   client:
     service-url:
       defaultZone:  http://user:1234@localhost:8761/eureka
logging:
   level:
     root: info

spring:
  application:
    name: provider-user


