server:
  port: 8080

spring:
    datasource:
      type:   com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
      data-username: xtp
      password: 1234

mybatis:
  type-aliases-package: com.xtp.pojo
  mapper-locations: classpath:mappers/*.xml


logging:
  level:
    com.xtp.mapper: debug

